# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [11]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import GoogleMaps_API_key

In [12]:
 # Configure gmaps with API key
gmaps.configure(GoogleMaps_API_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [13]:
 # Make a reference to the scatter_weather.csv file path
scatter_weather = "scatter_weather.csv"

# Import the books.csv file as a DataFrame
vacation_weather_df = pd.read_csv(scatter_weather)
vacation_weather_df

,City,Latitude,Longitude,Temperature,Max Temperature,Humidity,Cloudiness,Wind Speed
0,aberdeen,57.14,-2.10,35.62,42.01,69,0,10.29
1,abha,18.22,42.51,50.09,51.80,50,26,1.63
2,abilene,32.45,-99.73,40.84,44.60,55,1,8.05
3,abiramam,32.45,-99.73,39.45,41.00,52,1,8.05
4,ahipara,9.47,78.45,78.80,78.80,78,40,3.36
...,...,...,...,...,...,...,...,...
561,zhangye,17.02,54.09,71.60,71.60,60,40,4.70
562,zhengjiatun,-33.01,17.94,62.60,62.60,72,100,12.75
563,zhigansk,-10.62,150.67,91.08,91.08,50,9,9.64
564,znamenskoye,7.76,-73.39,82.02,82.02,57,91,6.93
565,zyryanovsk,29.42,-98.49,59.59,62.60,48,1,12.75

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [14]:
# Store 'Lat' and 'Lng' into  locations 
locations = vacation_weather_df[["Latitude", "Longitude"]].astype(float)

# Convert Poverty Rate to float and store
# HINT: be sure to handle NaN values
vacation_weather_df = vacation_weather_df.dropna()
humidity_value = vacation_weather_df["Humidity"].astype(float)

In [16]:
 # Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_value, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [20]:
# Filter out lattude values greater than zero create a Northern Hemisphere dataframe
perfect_weather_df = vacation_weather_df[vacation_weather_df['Max Temperature']<=80][vacation_weather_df['Max Temperature']>=70][vacation_weather_df['Wind Speed']<=10][vacation_weather_df['Cloudiness']==0]
perfect_weather_df

C:\Users\benja\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,City,Latitude,Longitude,Temperature,Max Temperature,Humidity,Cloudiness,Wind Speed
90,caravelas,7.53,-12.51,76.12,76.12,90,0,3.74
103,chokurdakh,-33.65,115.33,74.21,78.01,26,0,2.95
104,chuy,-33.65,115.33,75.33,79.00,24,0,2.95
211,jamestown,-29.14,-59.26,78.13,78.13,51,0,6.85
257,la seyne-sur-mer,7.43,3.28,71.06,71.06,85,0,0.96
380,pisco,-38.00,-57.56,75.34,77.00,47,0,9.17
381,pochutla,-38.00,-57.56,74.75,77.00,47,0,9.17
478,sur,16.78,94.73,78.94,78.94,38,0,4.41
522,vao,14.04,-83.39,74.62,74.62,87,0,5.57

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map